import { Container, Header } from "@/shared/components/shared";

export const Metadata = {
    title: 'Next Pizza | Warenkorb',
    description: 'Generated by Next.js',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
            <main className="min-h-screen bg-[#F4F1EE]">
                <Container className="max-w-7xl mx-auto">
                    <Header hasSearch={false} hasCart={false} className="border-gray-200" />
                    {children}
                </Container>
            </main>
    );
}